[package]
name = "led"
version = "0.1.0"
edition = "2018"
description = "Remotely send commands to RGB controller"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
